# Generated by Django 6.0.7 on 2026-07-24 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-date', '-created_time'], 'verbose_name': 'Gallery', 'verbose_name_plural': 'Gallery'},
        ),
    ]
